/** UniV3DualVault user-facing surface — mirrors stocklend/leverage/src/UniV3DualVault.sol 1:1 (no missing items). */
export const farmVaultAbi = [
  { type: "function", name: "LLTV", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "LOAN_IS_C0", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  {
    type: "function",
    name: "nextPositionId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "ownerOf",
    stateMutability: "view",
    inputs: [{ type: "uint256" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "positions",
    stateMutability: "view",
    inputs: [{ type: "uint256" }],
    outputs: [
      { name: "dexTokenId", type: "uint256" },
      { name: "liquidity", type: "uint128" },
      { name: "tickLower", type: "int24" },
      { name: "tickUpper", type: "int24" },
      { name: "debtRisk", type: "uint256" },
      { name: "debtLoan", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "positionValue",
    stateMutability: "view",
    inputs: [{ type: "uint256" }],
    outputs: [{ name: "valueInLoan", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalDebtInLoan",
    stateMutability: "view",
    inputs: [{ type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "isHealthy",
    stateMutability: "view",
    inputs: [{ type: "uint256" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "previewClose",
    stateMutability: "view",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "percent", type: "uint16" },
    ],
    outputs: [
      { name: "estGotRisk", type: "uint256" },
      { name: "estGotLoan", type: "uint256" },
      { name: "dueRisk", type: "uint256" },
      { name: "dueLoan", type: "uint256" },
      { name: "shortRisk", type: "uint256" },
      { name: "shortLoan", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "open",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "p",
        type: "tuple",
        components: [
          { name: "investRisk", type: "uint256" },
          { name: "investLoan", type: "uint256" },
          { name: "borrowRisk", type: "uint256" },
          { name: "borrowLoan", type: "uint256" },
          { name: "tickLower", type: "int24" },
          { name: "tickUpper", type: "int24" },
          { name: "amount0Min", type: "uint256" },
          { name: "amount1Min", type: "uint256" },
          { name: "minLiquidity", type: "uint128" },
          { name: "deadline", type: "uint256" },
        ],
      },
    ],
    outputs: [{ name: "positionNftId", type: "uint256" }],
  },
  {
    type: "function",
    name: "increase",
    stateMutability: "nonpayable",
    inputs: [
      { name: "id", type: "uint256" },
      {
        name: "p",
        type: "tuple",
        components: [
          { name: "investRisk", type: "uint256" },
          { name: "investLoan", type: "uint256" },
          { name: "borrowRisk", type: "uint256" },
          { name: "borrowLoan", type: "uint256" },
          { name: "amount0Min", type: "uint256" },
          { name: "amount1Min", type: "uint256" },
          { name: "minLiquidity", type: "uint128" },
          { name: "deadline", type: "uint256" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "harvest",
    stateMutability: "nonpayable",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "compound", type: "bool" },
      { name: "deadline", type: "uint256" },
    ],
    outputs: [
      { name: "out0", type: "uint256" },
      { name: "out1", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "addMargin",
    stateMutability: "nonpayable",
    inputs: [
      { name: "id", type: "uint256" },
      { name: "amountRisk", type: "uint256" },
      { name: "amountLoan", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "close",
    stateMutability: "nonpayable",
    inputs: [
      { name: "id", type: "uint256" },
      {
        name: "c",
        type: "tuple",
        components: [
          { name: "percent", type: "uint16" },
          { name: "topUpRisk", type: "uint256" },
          { name: "topUpLoan", type: "uint256" },
          { name: "maxSwapIn", type: "uint256" },
          { name: "minOutRisk", type: "uint256" },
          { name: "minOutLoan", type: "uint256" },
          { name: "zapPath", type: "bytes" },
          { name: "deadline", type: "uint256" },
        ],
      },
    ],
    outputs: [
      { name: "outRisk", type: "uint256" },
      { name: "outLoan", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "rebalance",
    stateMutability: "nonpayable",
    inputs: [
      { name: "id", type: "uint256" },
      {
        name: "p",
        type: "tuple",
        components: [
          { name: "newTickLower", type: "int24" },
          { name: "newTickUpper", type: "int24" },
          { name: "swapAmount", type: "int256" },
          { name: "minSwapOut", type: "uint256" },
          { name: "minLiquidity", type: "uint128" },
          { name: "zapPath", type: "bytes" },
          { name: "deadline", type: "uint256" },
        ],
      },
    ],
    outputs: [],
  },
] as const;
