name: Run vitest
on:
  pull_request:
    branches:
      - "main"
      - "release"
  push:
    branches:
      - "main"
jobs:
  vitest:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22]
    env:
      VITE_WALLET_KIT_PROJECT_ID: ${{ secrets.VITE_WALLET_KIT_PROJECT_ID }}
      VITE_APP_TITLE: ${{ vars.VITE_APP_TITLE }}
      VITE_ERPC_API_KEY: ${{ secrets.VITE_ERPC_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build UIKit
        run: pnpm run uikit:build
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10 # v1
      - name: Create .env
        run: |
          echo "VITE_WALLET_KIT_PROJECT_ID=${{ env.VITE_WALLET_KIT_PROJECT_ID }}" >> apps/lite/.env
          echo "VITE_APP_TITLE=${{ env.VITE_APP_TITLE }}" >> apps/lite/.env
          echo "VITE_ERPC_API_KEY=${{ env.VITE_ERPC_API_KEY }}" >> apps/lite/.env
      - name: Test
        run: pnpm vitest
