name: Deploy site via Fleek
on:
  push:
    branches: ["release"]
    paths: ["pnpm-lock.yaml", "fleek.config.ts", "packages/uikit/**", "apps/fallback/**"]
jobs:
  deploy-to-fleek:
    # Create an environment for static hosting on IPFS
    environment:
      name: IPFS
      url: ${{ steps.build-and-deploy.outputs.ipfs_cid }}

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22]
    env:
      FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
      FLEEK_PROJECT_ID: ${{ secrets.FLEEK_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Fleek CLI
        run: pnpm add -g @fleek-platform/cli
      - name: Build & deploy sites
        id: build-and-deploy
        run: |
          fleek sites deploy
          echo "ipfs_cid=https://$(fleek sites deployments --slug morpho-fallback | tail -n +4 | head -n 1 | awk '{print $NF}').ipfs.dweb.link/" >> $GITHUB_OUTPUT
